In [1]:
from implementations import *

In [2]:
y = np.array([0.1, 0.3, 0.5])
tx = np.array([[2.3, 3.2],
       [1. , 0.1],
       [1.4, 2.3]])
initial_w = np.array([0.5, 1. ])

ridge_regression(y,tx, 0)

(array([ 0.2187858 , -0.05383734]), np.float64(0.026941580756013744))

In [3]:
y = np.array([0.1, 0.3, 0.5])
tx = np.array([[2.3, 3.2],
       [1. , 0.1],
       [1.4, 2.3]])

ridge_regression(y,tx,0)

(array([ 0.2187858 , -0.05383734]), np.float64(0.026941580756013744))

In [13]:
y = np.array([0., 1., 1.])
tx = np.array([[2.3, 3.2],
       [1. , 0.1],
       [1.4, 2.3]])
initial_w = np.array([0.5, 1. ])

logistic_regression(y,tx, initial_w,1000, 0.005)

(array([ 0.1836088 , -0.19425505]), 0.6684888384786872)

NameError: name 'float128' is not defined